### ISSUE TITLE
backbone算法测试

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/HV_YOLO#10]
要求：
１．常用的backbone运行没有问题
２．常使用的backbone使用cifar100训练分类任务精度
３．与其他人训练的精度做对比
４．输出每个backbone的分类精度文档

**Comment by MiniBullLab** [comment]
阶段训练结果记录

**Comment by kingwangxiang** [comment]
1.测试分类任务。
1)使用backbone网络resnet18，测试数据cifar100 ，迭代200epoch，模型测试精度77.9。
2)使用Multi-stage策略更新学习率lr，其中某几个阶段的学习率，loss值几乎保持不降，有几个阶段的学习率使loss骤降。Multi-stage更新学习率策略，可以做些适当优化调整。

**Comment by lpj0822** [comment]
好的，看看其他backbone的一些情况，看有没有规律

**Comment by kingwangxiang** [comment]
2.测试分类任务。
1)使用backbone网络mobilenetv3_large，测试数据cifar100 ，迭代200epoch，模型测试精度59.38。
2)精度上比resnet18差很多。

**Comment by lpj0822** [comment]
@kingwangxiang 使用最新的develop分支代码测试

**Comment by lpj0822** [comment]
在easyai/model/cls/classnet.py文件中修改backbone，然后训练模型精度

**Comment by kingwangxiang** [comment]
好的
