### ISSUE TITLE
建立测试集

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/HV_YOLO#19]
1. 建立分类，检测，分割的日常测试集和标准测试集，要求日常测试集不得超过5万张。
2. 建立测试集的基础精度作为后续的训练基线
3. 记录所有的精度测试并绘制成表格存档
@lpj0822 @kingwangxiang

**Comment by lpj0822** [comment]
先不着急建这个，先把develop分支代码测通，这个代码仓库要删掉，这个issue就没了
@foww-0001
